### ISSUE TITLE
Cannot change conservation mode on Ideapad S540 13ARE

### ISSUE THREAD

**Issue by imunique-ZJ** [laurento/gnome-shell-extension-ideapad#8] opened 2021-05-03 00:58 UTC
I was able to change conservation mode, however, it doesn't work after I upgraded the kernel to 5.12 (via mainline).
I tried the commands but got `Input/Output error`...

```
$ ls /sys/bus/platform/drivers/ideapad_acpi/
bind  module  uevent  unbind  VPC2004:00

$ echo "0" | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode > /dev/null
tee: '/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode': Input/output error
```

OS: Ubuntu 20.04
Kernel: 5.12.1

**Comment by laurento** [comment] 2021-05-05 18:32
What you're describing doesn't seem to be an issue with the extension. For this reason, I'm going to close this issue.

BTW it looks like you're not alone, have a [look here for instance](https://superuser.com/questions/1646358/input-output-error-when-activating-lenovo-ideapad-conservation-mode).

**Closed by laurento** 2021-05-05 18:32 UTC

**Comment by f-fouad** [comment] 2021-05-17 19:29
It is a regression on kernel version 5.12. A [patch](https://bugzilla.kernel.org/show_bug.cgi?id=213109) has been sent to fix it.

**Comment by laurento** [comment] 2021-05-18 18:52
Thanks for the follow up.
